#!/bin/bash

#! Setup 'today_date' that will need to be used by following processes
today_date=`date +%m%d%y`
echo "today_date="$today_date

#! Prepare logdir
logdir="/tmp/logsSS_$today_date"
mkdir -p $logdir
rm -rf $logdir/*

#! 1. Obtain per_non_vst_SE results
#! + This process tags all its output with 'today_date', which needs to be used by subsequent processes
dev/dobs_per_non_vst_SE_result_SSBands >&  $logdir/dobs_per_non_vst_SE_result_SSBands.log & 
dev/dobs_per_non_vst_SE_result_CCcut   >&  $logdir/dobs_per_non_vst_SE_result_CCcut.log &
#! Wait for processes in 1 to finish before moving on
wait

#! 2. Using per_non_vst_SE results from 1, obtain cmb_non_vst_SE
#! Note that the following script needs the correct date tagged results from 1,
#! which can be entered in MMDDYY format, else it defaults to todays date 
dev/dobs_cmb_non_vst_SE_result $today_date >& $logdir/dobs_cmb_non_vst_SE_result.log &
#! Wait for processes in 2 to finish before moving on
wait


#! 3. Using cmb_non_vst_SE from 1 to obtain cmb_vst_SE
#! Note that the following script needs the correct date tagged results from 1,
#! which can be entered in MMDDYY format, else it defaults to todays date
dev/dobs_cmb_vst_SE_result  $today_date >& $logdir/dobs_cmb_vst_SE_result.log &
#! Wait for processes in 3 to finish before moving on
wait

#! To make SE plots for a particular OBSDIR
#! NOTE that the date has to be manually adjusted
#! 1. First do each of the per_non_vst_SE
plot_SE.py $OBSDIR_E16/SS/dbg/lowQ2_fixMM2cut_062416_sim4_sim5_sim6_sim7_sim8_sim13_$today_date/ >& $logdir/plot_SE_per_non_vst_SE_result_SSBands.log &
plot_SE.py $OBSDIR_E16/SS/dbg/lowQ2_CC_cut_080216_sim4_sim5_sim6_sim7_sim8_sim13_$today_date/ >& $logdir/plot_SE_per_non_vst_SE_result_CCcut.log &
#! 2. Now do the cmb_non_vst_SE
plot_SE.py $OBSDIR_E16/SS/dbg/lowQ2_cmb_non_vst_SE_$today_date >& $logdir/plot_SE_cmb_non_vst_SE_result.log&
#! 3. Now do the cmb_vst_SE
plot_SE.py $OBSDIR_E16/SS/dbg/lowQ2_cmb_vst_SE_$today_date >& $logdir/plot_SE_cmb_vst_SE_result.log&
