#!/usr/bin/python
from proc_yields_lite import ProcYieldsLite
from disp_yields_lite import DispYieldsLite
import sys

'''
dy_integ [obsdir] [simnum=siml]
'''
#! Get obsdir
if len(sys.argv)==1:
        sys.exit("Please enter obsdir")
else:
        obsdir=sys.argv[1]

#! User input simnum, else use siml
if len(sys.argv)>2:
	simnum=sys.argv[2]
else:
	simnum='siml'

print "Displaying integrated yields for obsdir:sim = %s:%s"%(obsdir,simnum)

dy_lite=DispYieldsLite(obsdir,simnum=simnum)
#dy.disp_integ_yield()
dy_lite.disp_integ_yield(vst='VST1',norm=True)
#dy.disp_integ_yield(vst='VST2',norm=True)
#dy.disp_integ_yield(vst='VST3',norm=True)
