#!/bin/bash
#! + Use SSBands-cutsncors1 = gpart-pid*stat-pid=off*off
dbg=${1:-"False"}
#echo $dbg

EXTRACT_D_E_FOR_NON_ALPHA=False

#! lQ2
dobs_R2 mthd2:False $EXTRACT_D_E_FOR_NON_ALPHA $OBSDIR_E16/lowQ2_SSBands_092516/cutsncors1  sim4_sim5_sim6_sim7_sim8_sim13 EC_EF_ST  2.00 3.00 1.400 2.125 e16 $dbg
#! hQ2
dobs_R2 mthd2:False $EXTRACT_D_E_FOR_NON_ALPHA $OBSDIR_E16/highQ2_SSBands_092516/cutsncors1 sim9_sim10_sim11_sim12         EC_EF_ST  3.00 5.00 1.400 2.125 e16 $dbg
