/********************************************************************
* ep_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ep_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableep_dict();
extern void G__cpp_setup_inheritanceep_dict();
extern void G__cpp_setup_typetableep_dict();
extern void G__cpp_setup_memvarep_dict();
extern void G__cpp_setup_globalep_dict();
extern void G__cpp_setup_memfuncep_dict();
extern void G__cpp_setup_funcep_dict();
extern void G__set_cpp_environmentep_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "data_h10.h"
#include "particle_constants.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ep_dictLN_TString;
extern G__linked_taginfo G__ep_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ep_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ep_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ep_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ep_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ep_dictLN_TTree;
extern G__linked_taginfo G__ep_dictLN_TBranch;
extern G__linked_taginfo G__ep_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ep_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ep_dictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TLorentzVector;
extern G__linked_taginfo G__ep_dictLN_H10Typ;
extern G__linked_taginfo G__ep_dictLN_DataH10;
extern G__linked_taginfo G__ep_dictLN_DataH10cLcLtmp;
extern G__linked_taginfo G__ep_dictLN_ParticleConstants;
extern G__linked_taginfo G__ep_dictLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR;

/* STUB derived class for protected member access */
