/********************************************************************
* ep_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ep_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableep_dict();
extern void G__cpp_setup_inheritanceep_dict();
extern void G__cpp_setup_typetableep_dict();
extern void G__cpp_setup_memvarep_dict();
extern void G__cpp_setup_globalep_dict();
extern void G__cpp_setup_memfuncep_dict();
extern void G__cpp_setup_funcep_dict();
extern void G__set_cpp_environmentep_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "data_h10.h"
#include "data_ana.h"
#include "data_eid.h"
#include "data_efid.h"
#include "data_skim_q.h"
#include "data_mom.h"
#include "data_pid.h"
#include "data_ekin.h"
#include "data_top.h"
#include "sel_h10.h"
#include "particle_constants.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ep_dictLN_TClass;
extern G__linked_taginfo G__ep_dictLN_TBuffer;
extern G__linked_taginfo G__ep_dictLN_TDirectory;
extern G__linked_taginfo G__ep_dictLN_TMemberInspector;
extern G__linked_taginfo G__ep_dictLN_TObject;
extern G__linked_taginfo G__ep_dictLN_TNamed;
extern G__linked_taginfo G__ep_dictLN_TString;
extern G__linked_taginfo G__ep_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ep_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ep_dictLN_TList;
extern G__linked_taginfo G__ep_dictLN_TObjArray;
extern G__linked_taginfo G__ep_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ep_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ep_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ep_dictLN_TFile;
extern G__linked_taginfo G__ep_dictLN_TTree;
extern G__linked_taginfo G__ep_dictLN_TBranch;
extern G__linked_taginfo G__ep_dictLN_TObjString;
extern G__linked_taginfo G__ep_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__ep_dictLN_TSelector;
extern G__linked_taginfo G__ep_dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ep_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ep_dictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__ep_dictLN_TLorentzVector;
extern G__linked_taginfo G__ep_dictLN_DataH10;
extern G__linked_taginfo G__ep_dictLN_DataH10cLcLtmp;
extern G__linked_taginfo G__ep_dictLN_DataEid;
extern G__linked_taginfo G__ep_dictLN_DataEFid;
extern G__linked_taginfo G__ep_dictLN_DataSkimQ;
extern G__linked_taginfo G__ep_dictLN_DataMom;
extern G__linked_taginfo G__ep_dictLN_DataPid;
extern G__linked_taginfo G__ep_dictLN_DataEkin;
extern G__linked_taginfo G__ep_dictLN_DataTop;
extern G__linked_taginfo G__ep_dictLN_DataTopcLcLvars;
extern G__linked_taginfo G__ep_dictLN_DataAna;
extern G__linked_taginfo G__ep_dictLN_DataAnacLcLh8Dbng;
extern G__linked_taginfo G__ep_dictLN_TStopwatch;
extern G__linked_taginfo G__ep_dictLN_TProofOutputFile;
extern G__linked_taginfo G__ep_dictLN_ParticleConstants;
extern G__linked_taginfo G__ep_dictLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__ep_dictLN_EpProcessor;
extern G__linked_taginfo G__ep_dictLN_SelH10;
extern G__linked_taginfo G__ep_dictLN_vectorlEEpProcessormUcOallocatorlEEpProcessormUgRsPgR;
extern G__linked_taginfo G__ep_dictLN_reverse_iteratorlEvectorlEEpProcessormUcOallocatorlEEpProcessormUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
