#!/bin/bash
nentries=${1:-1000000000}
#ana -i h10.lst -t e1f:sim:2pi -p d2piT:eid:efid:qskim:pid:d2piR -n $nentries
proc_h10.py --h10type=e1f:sim:2pi --output=d2pi --q2w=q2w1 --sim_num=sim1 --nentries=$nentries
