#!/usr/bin/python
import sys
from study_elastic_tools import StudyElasticTools

'''
dy_elastic [obsdir] [sctr_bng=central] [mthd=1] [thry=wrad]
'''

if len(sys.argv)<2:
	sys.exit("Enter obsdir")
else:
	obsdir=sys.argv[1]

if len(sys.argv)>=3: #! i.e. user entered sctr_bng option
        if (sys.argv[2]=="full"):
                sctr_bng="full"
        elif (sys.argv[2]=="central"):
                sctr_bng="central"
        else:
                sys.exit("sctr_bng=%s not recognize"%sys.argv[2])
else:
        sctr_bng="central"

if len(sys.argv)>=4: #! i.e. user entered mthd option
        mthd=int(sys.argv[3])
else:
        mthd=1

if len(sys.argv)>=5: #! user entered thry option
	thry=sys.argv[4]
else:
	thry='wrad'

if 'obs_030815' in obsdir:
	wcut=1.1
elif 'obs_082615' in obsdir or 'obs_082715' in obsdir:
	wcut=1.028
else:
	wcut=1.0

print "Going to display Elastic Cross Sections for obsdir=%s,sctr_bng=%s,mthd=%d,thry=%s,wcut=%.3f"%(obsdir,sctr_bng,mthd,thry,wcut)
t=StudyElasticTools(obsdir,sctr_bng)
t.disp_yields(mthd,thry,wcut)
