#!/usr/bin/python
import sys
from study_elastic_tools import StudyElasticTools

'''
dy_elastic [obsdate] [thry=wrad]
'''

if len(sys.argv)<2:
	sys.exit("Enter obsdate")
else:
	obsdate=sys.argv[1]

if len(sys.argv)>2: #! user entered thry option
	thry=sys.argv[2]
else:
	thry='wrad'

if obsdate=='obs_030815':
	wcut=1.1
elif obsdate=='obs_032715':
	wcut=1.0
print "Going to display Elastic Cross Sections for obsdate=%s,thry=%s,wcut=%.1f"%(obsdate,thry,wcut)
t=StudyElasticTools(obsdate)
t.disp_yields(thry,wcut)
