#!/usr/bin/python
from disp_obs import DispObs
import sys

#! ---------------------
#  + Usage=dobs_SS [expt=e16] [dbg=False]
#  + SS inputs (dobsd, SS_tag) have to be entered manually
#  + NOTE, 'SS_tag' is used to name the output created
#!----------------------

#! *** Setup global parameters ***
#! Q2 limits for lowQ2
Q2MIN_LOW_Q2=2.00
Q2MAX_LOW_Q2=3.00
#! Q2 limits for highQ2
Q2MIN_HIGH_Q2=3.00
Q2MAX_HIGH_Q2=5.00
#! W limits
WMIN=1.400
WMAX=2.125

#! Get inputs from user
if len(sys.argv)>1: #! User input expt 
        expt=sys.argv[1]
        if expt!='e1f' and expt!='e16':
                sys.exit("expt=e1f or e16 only.")
else:
        expt='e16'

if len(sys.argv)>2: #! User input dbg, else use dbg=False
        if sys.argv[2]=="False":
                dbg=False
        elif sys.argv[2]=="True":
                dbg=True
        else:
                print "Please enter dbg=True or False!"
                sys.exit()
else:
        dbg="False"

#! Manual inputs for SS
#! syntax for obsd={obsnum:['obsdir','obstag']}

#! SS-Obs from h10_skim_e
#!=======================
#! + lowQ2
#obsd={
#       1:['obs_dflt_eff_scpd_at_mod_dflt_lowQ2_SS3_022216/sim4_sim5_sim6_sim7',                       'eff_scpd_atmod'],
#       2:['obs_dflt_dflt_ECfid-on_lowQ2_SS3_022216/sim4_sim5_sim6_sim7',                              'ECfid-on'],
#       3:['obs_dflt_dflt_ECfid-on_at_mod_lowQ2_SS3_022216//sim4_sim5_sim6_sim7',                      'ECfid-on_atmod'],
#       4:['obs_dflt_eff_scpd_at_mod_:11:1:2:3:13:14:15:_at_mod_lowQ2_SS3_022316/sim4_sim5_sim6_sim7', 'EI-cuts_atmod'],
#       5:['obs_dflt_eff_scpd_at_mod_dflt_ECfid-on_lowQ2_SS3_022516/sim4_sim5_sim6_sim7',              'eff_scpd_atmod_ECfid-on'],
#       6:['obs_dflt_eff_scpd_at_mod_dflt_ECfid-on_at_mod_lowQ2_SS3_022516/sim4_sim5_sim6_sim7',       'eff_scpd_atmod_ECfid-on_atmod']
#}
#SS_tag='lowQ2_sim4_sim5_sim6_sim7'
#print "Displaying SS-obs for obsdir q2min q2max wmin wmax expt dbg",'NA',Q2MIN_LOW_Q2,Q2MAX_LOW_Q2,WMIN,WMAX,expt,dbg
#print "obsd=",obsd
#print "SS_tag=",SS_tag
#do=DispObs('NA','NA','NA',Q2MIN_LOW_Q2,Q2MAX_LOW_Q2,WMIN,WMAX,expt,dbg,obsd=obsd,SS_tag=SS_tag)
#do.disp_1D_SS()
#! + highQ2
#obsd={
#       1:['obs_dflt_eff_scpd_at_mod_dflt_highQ2_SS3_022216/sim9',                       'eff_scpd_atmod'],
#       2:['obs_dflt_dflt_ECfid-on_highQ2_SS3_022216/sim9',                              'ECfid-on'],
#       3:['obs_dflt_dflt_ECfid-on_at_mod_highQ2_SS3_022216/sim9',                      'ECfid-on_atmod'],
#       4:['obs_dflt_eff_scpd_at_mod_:11:1:2:3:13:14:15:_at_mod_highQ2_SS3_022316/sim9', 'EI-cuts_atmod'],
#       5:['obs_dflt_eff_scpd_at_mod_dflt_ECfid-on_highQ2_SS3_022516/sim9',              'eff_scpd_atmod_ECfid-on'],
#       6:['obs_dflt_eff_scpd_at_mod_dflt_ECfid-on_at_mod_highQ2_SS3_022516/sim9',       'eff_scpd_atmod_ECfid-on_atmod']
#}
#SS_tag='highQ2_sim9'
#print "Displaying SS-obs for obsdir q2min q2max wmin wmax expt dbg",'NA',Q2MIN_HIGH_Q2,Q2MAX_HIGH_Q2,WMIN,WMAX,expt,dbg
#print "obsd=",obsd
#print "SS_tag=",SS_tag
#do=DispObs('NA','NA','NA',Q2MIN_HIGH_Q2,Q2MAX_HIGH_Q2,WMIN,WMAX,expt,dbg,obsd=obsd,SS_tag=SS_tag)
#do.disp_1D_SS()

#! SS-Obs from h10_skim_SS
#!==========================
#! + lowQ2
obsd={
       1:['obs_dflt_eff_scpd_at_mod_dflt_lowQ2_SS3_from-h10-skim-SS_prll_030416/sim4_sim5_sim6_sim7',                       'eff_scpd_atmod'],
       2:['obs_dflt_dflt_ECfid-on_lowQ2_SS3_from-h10-skim-SS_prll_030416/sim4_sim5_sim6_sim7',                        'ECfid-on'],
       3:['obs_dflt_dflt_ECfid-on_at_mod_lowQ2_SS3_from-h10-skim-SS_prll_030416//sim4_sim5_sim6_sim7',                      'ECfid-on_atmod'],
       4:['obs_dflt_eff_scpd_at_mod_:11:1:2:3:13:14:15:_at_mod_lowQ2_SS3_from-h10-skim-SS_prll_030416/sim4_sim5_sim6_sim7', 'EI-cuts_atmod'],
       5:['obs_dflt_eff_scpd_at_mod_dflt_ECfid-on_lowQ2_SS3_from-h10-skim-SS_prll_030416/sim4_sim5_sim6_sim7',              'eff_scpd_atmod_ECfid-on'],
       6:['obs_dflt_eff_scpd_at_mod_dflt_ECfid-on_at_mod_lowQ2_SS3_from-h10-skim-SS_prll_030416/sim4_sim5_sim6_sim7',       'eff_scpd_atmod_ECfid-on_atmod']
}
SS_tag='lowQ2_sim4_sim5_sim6_sim7_from-h10-skim-SS_prll_030416'
print "Displaying SS-obs for obsdir q2min q2max wmin wmax expt dbg",'NA',Q2MIN_LOW_Q2,Q2MAX_LOW_Q2,WMIN,WMAX,expt,dbg
print "obsd=",obsd
print "SS_tag=",SS_tag
do=DispObs('NA','NA','NA',Q2MIN_LOW_Q2,Q2MAX_LOW_Q2,WMIN,WMAX,expt,dbg,obsd=obsd,SS_tag=SS_tag)
do.disp_1D_SS()

#! +highQ2
obsd={
       1:['obs_dflt_eff_scpd_at_mod_dflt_highQ2_SS3_from-h10-skim-SS_prll_030416/sim9',                       'eff_scpd_atmod'],
       2:['obs_dflt_dflt_ECfid-on_highQ2_SS3_from-h10-skim-SS_prll_030416/sim9',                        'ECfid-on'],
       3:['obs_dflt_dflt_ECfid-on_at_mod_highQ2_SS3_from-h10-skim-SS_prll_030416//sim9',                      'ECfid-on_atmod'],
       4:['obs_dflt_eff_scpd_at_mod_:11:1:2:3:13:14:15:_at_mod_highQ2_SS3_from-h10-skim-SS_prll_030416/sim9', 'EI-cuts_atmod'],
       5:['obs_dflt_eff_scpd_at_mod_dflt_ECfid-on_highQ2_SS3_from-h10-skim-SS_prll_030416/sim9',              'eff_scpd_atmod_ECfid-on'],
       6:['obs_dflt_eff_scpd_at_mod_dflt_ECfid-on_at_mod_highQ2_SS3_from-h10-skim-SS_prll_030416/sim9',       'eff_scpd_atmod_ECfid-on_atmod']
}
SS_tag='highQ2_sim9_from-h10-skim-SS_prll_030416'
print "Displaying SS-obs for obsdir q2min q2max wmin wmax expt dbg",'NA',Q2MIN_HIGH_Q2,Q2MAX_HIGH_Q2,WMIN,WMAX,expt,dbg
print "obsd=",obsd
print "SS_tag=",SS_tag
do=DispObs('NA','NA','NA',Q2MIN_HIGH_Q2,Q2MAX_HIGH_Q2,WMIN,WMAX,expt,dbg,obsd=obsd,SS_tag=SS_tag)
do.disp_1D_SS()
