#!/usr/bin/python
from proc_h8 import ProcH8
import sys,time

"""
ph8 [obsdir] [simnum=siml] [q2min=1.50] [q2max=5.00] [wmin=1.400] [wmax=2.125] [acc_cut=-1] [acc_rel_err_cut=-1] [usehel=False] [do_etgt_BG_sub=True] [dbg=False]
"""
if len(sys.argv)<3:
	sys.exit("Not all parameters entered. obsdir and dtyps are required")

obsdir=sys.argv[1]

#dtypl=[]
#for dtyp in sys.argv[2].split(":"):
#	if dtyp!="sim" and dtyp!="exp":
#		sys.exit("valid dtyps are sim and exp only!")
#	dtypl.append(dtyp)

if len(sys.argv)>2:#i.e. simnum entered by user
	simnum=sys.argv[2]
else:
	simnum='siml'

if len(sys.argv)>3:#i.e. q2min entered by user
	q2min=float(sys.argv[3])
else:
        q2min=1.50

if len(sys.argv)>4:#i.e. q2max entered by user
        q2max=float(sys.argv[4])
else:
        q2max=5.00

if len(sys.argv)>5:#i.e. wmin entered by user
        wmin=float(sys.argv[5])
else:
        wmin=1.400

if len(sys.argv)>6:#i.e. wmax entered by user
        wmax=float(sys.argv[6])
else:
        wmax=2.125

if len(sys.argv)>7:#i.e. acc_cut 
        acc_cut=float(sys.argv[7])
else:
        acc_cut=-1

if len(sys.argv)>8:#i.e. acc_rel_err_cut 
        acc_rel_err_cut=float(sys.argv[8])
else:
        acc_rel_err_cut=-1

if len(sys.argv)>9:#i.e. usehel entered by user
        if   sys.argv[9]=='True':  usehel=True
        elif sys.argv[9]=='False': usehel=False
        else: sys.exit("usehel=\'%s\' not valid. Exiting."%sys.argv[9])

else:
        usehel=False

if len(sys.argv)>10:#i.e. do_etgt_BG_sub entered by user
        if   sys.argv[10]=='True':  do_etgt_BG_sub=True
        elif sys.argv[10]=='False': do_etgt_BG_sub=False
        else: sys.exit("do_etgt_BG_sub=\'%s\' not valid. Exiting"%sys.argv[10])
else:
        dbg=False

if len(sys.argv)>11:#i.e. dbg entered by user
        if   sys.argv[11]=='True':  dbg=True
        elif sys.argv[11]=='False': dbg=False
        else: sys.exit("dbg=\'%s\' not valid. Exiting"%sys.argv[11])
else:
        dbg=False

print "ph8: Going to process h8 for (obsdir simmnum q2min q2max wmin wmax acc_cut acc_rel_err_cut usehel debug)=(", obsdir,simnum,q2min,q2max,wmin,wmax,acc_cut,acc_rel_err_cut,usehel,dbg,")"
time.sleep(3)
#for dtyp in dtypl:
ph8=ProcH8(obsdir,simnum=simnum,q2min=q2min,q2max=q2max,wmin=wmin,wmax=wmax,acc_cut=acc_cut,acc_rel_err_cut=acc_rel_err_cut,usehel=usehel,dbg=dbg)#,wmin=1.725)
ph8.execute()
