#!/bin/bash
nentries=${1:-0}

#! [10-25-15] 
#! + Removed qskim to match with 'lite'
#!    + Code appropriately changed in ProcPidNew,ProcPFidNew
proc_h10 -i h10_main.lst -t e1f:exp:2pi  -p eid:efid:mom:pidnewmon:pfidnew:q2wskimR:d2piR_tree_BG -o d2piR_hvy.root -n $nentries
