#!/usr/bin/python
import os,subprocess,glob,sys
"""
>>> ay sim1 sim2 ... simN
On executing this script, the following happens, in $D2PIDIR_SIM:
1. A list of each individual simulation (simX) is obtained
    + If user does specify simXs, then by default all of the simXs in $D2PIDIR_SIM are used
2. An output directory to store result of cumulative simulation (cum_sim=simXsimYsimZ)
   created.
3. Finally the d2pi from each individual simulation is added and put into cum_sim
"""

datadir=os.environ['D2PIDIR_SIM']

#! 1. Get list of all sims
if len(sys.argv)>=2:
    siml=[]
    for i in range(len(sys.argv)):
        if i==0: continue
        siml.append(sys.argv[i])
else:
    siml=glob.glob(os.path.join(datadir,'sim[0-9]'))
    siml+=glob.glob(os.path.join(datadir,'sim[0-9][0-9]'))
    siml=[os.path.basename(i) for i in siml]
    siml.sort()
print "List of individual simulations=",siml

#! 2. Prepare outdir
siml_pretty=[int(i.strip("sim")) for i in siml]
siml_pretty=map(int,siml_pretty)
print siml_pretty
siml_pretty=sorted(siml_pretty)
siml_pretty=["sim%02d"%i for i in siml_pretty]
print siml_pretty
cum_sim="".join(siml_pretty)
print "Cumulative simulation result will be stored in:", cum_sim
outdir=os.path.join(datadir,cum_sim)
if not os.path.exists(outdir):
    os.makedirs(outdir)

#! 3. Finally, do 'hadd targetfile sourcefile1 sourcefile2 ... sourcefileN'
fl=['d2piT.root','d2piR.root']
for f in fl:
    tf=os.path.join(outdir,f)
    sfl=[]
    for sim in siml:
        sfl.append(os.path.join(datadir,sim,f))
    sfl=sorted(sfl)
    cmd=["hadd",tf]
    cmd+=sfl
    print ">>>%s\n"%cmd
    subprocess.call(cmd)
