#!/usr/bin/python
from proc_yields import ProcYields
from disp_yields import DispYields
import sys

#! ---------------------
#  dR2 [obsdir] [R2s=A:B:C:D] [mthd=mthd1] [viewl=view1:view2] [plotphiproj=False] [simnum=siml]
#!----------------------

#! Get obsdir
if len(sys.argv)==1:
        sys.exit("Please enter obsdir")
else:
        obsdir=sys.argv[1]

if len(sys.argv)>=3: #i.e. User input R2s
        R2l=sys.argv[2].split(":")
else:
        R2l=['A','B','C','D']

if len(sys.argv)>=4: #i.e. User input mthd 
        mthd=sys.argv[3]
else:
        mthd='mthd1'

if len(sys.argv)>=5: #i.e. User input viewl 
        viewl=sys.argv[4].split(":")
else:
        viewl=["view1","view2"]

if len(sys.argv)>=6: #i.e. User input plotphiproj 
        if   sys.argv[5]=="True": plotphiproj=True
	elif sys.argv[5]=="False":plotphiproj=False
else:
        plotphiproj=False

if len(sys.argv)==7: #i.e. User input simnum, else use siml
	simnum=sys.argv[6]
else:
	simnum='siml'

print "Displaying Obs-R2: R2l=%s,mthd=%s,viewl=%s,plotphiproj=%s,simnum=%s"%(R2l,mthd,viewl,plotphiproj,simnum)
dy=DispYields(obsdir,simnum)
dy.disp_obs_R2(R2l=R2l,mthd=mthd,viewl=viewl,plotphiproj=plotphiproj,q2min=1.25,q2max=1.75,wmin=1.300,wmax=3.000,dtypl=['EXP','SIM'],seql=['C','F'])
