#!/usr/bin/python
from proc_yields import ProcYields
from disp_yields import DispYields
import sys

#! ---------------------
#  dR2 [simnum]
#!----------------------

if len(sys.argv)>2: #i.e. User input simnum, else use siml
	simnum=sys.argv[2]
else:
	simnum='siml'

print "Displaying Obs-R2: %s"%(simnum)
dy=DispYields(simnum)

#dy.disp_R2(R2='D',q2min=1.25,q2max=1.75,hel='POS',dtypl=['EXP'],seql=['C','F'])
#dy.disp_R2(R2='D',q2min=1.25,q2max=1.75,hel='NEG',dtypl=['EXP'],seql=['C','F'])

dy.disp_R2(R2='A',q2min=1.25,q2max=1.75,hel='UNPOL',dtypl=['EXP','SIM'],seql=['C','F'])
dy.disp_R2(R2='A',q2min=1.25,q2max=1.75,hel='POS',  dtypl=['EXP','SIM'],seql=['C','F'])
dy.disp_R2(R2='A',q2min=1.25,q2max=1.75,hel='NEG',  dtypl=['EXP','SIM'],seql=['C','F'])
