#!/usr/bin/python
from proc_yields import ProcYields
from disp_yields import DispYields
import sys

#! ---------------------
#  dy [view] [simnum]
#!----------------------
 
#! User input simnum, else use siml
if len(sys.argv)<3:
	simnum='siml'
else:
	simnum=sys.argv[2]

print "Displaying 1D-Obs: %s,%s"%(sys.argv[1],simnum)

dy=DispYields(simnum)
dy.disp_1D(view=sys.argv[1])
