#!/usr/bin/python
from proc_yields import ProcYields
from disp_yields import DispYields
import sys

'''
dy_integ [obsdate] [simnum=siml] [tops=tops]
'''
#! Get obsdate
if len(sys.argv)==1:
        sys.exit("Please enter obsdate")
else:
        obsdate=sys.argv[1]

#! User input simnum, else use siml
if len(sys.argv)>2:
	simnum=sys.argv[2]
else:
	simnum='siml'

if len(sys.argv)>3:#i.e. tops by user
        tops=[]
        if len(sys.argv[3].split(":"))>0:
                for top in map(int,sys.argv[3].split(":")):
                        if top!=1 and top!=2 and top!=3 and top!=4:
                                sys.exit("valid tops are 1,2,3 and 4 only!")
                        tops.append(top)
        else:
                sys.exit("Please enter tops as 1:2:3:4")
else:
        tops=[1,2,3,4]

print "Displaying integrated yields for obsdate:sim:tops = %s:%s:%s"%(obsdate,simnum,tops)

dy=DispYields(obsdate,simnum=simnum,tops=tops)
#dy.disp_integ_yield()
dy.disp_integ_yield(vst='VST1',norm=True)
dy.disp_integ_yield(vst='VST2',norm=True)
dy.disp_integ_yield(vst='VST3',norm=True)
