#!/usr/bin/python
from proc_yields import ProcYields
from disp_yields import DispYields

import collections

#for q2w in ['q2w1','q2w2','q2w3','q2w4']:
for q2w in ['q2w1']:#,'q2w3','q2w4']:
	dy=DispYields(q2w)
	y=dy.get_integ_yield()
        for seq in ['C','H','F']:
        	oy=collections.OrderedDict(sorted(y[seq].items()))
                print "yield for",seq
                print oy
        #print y['C']
	#print y['H']
	#print y['F']
