#!/bin/bash
#at-h8 sim_num=$1
#at-h8 q2w_num=$2
nentries=${1:-1000000000}

echo "*** Making /sim/sim$sim_num/q2w$q2w_num/d2pi.root *** "
echo ">>> ls -lrt $OBS_DATADIR_SIM/sim$sim_num/q2w$q2w_num"
ls -lrt $OBS_DATADIR_SIM/sim$sim_num/q2w$q2w_num
#at-h8 proc_h10.py --h10type=e1f:sim:2pi --output=d2pi --sim_num=sim$sim_num --q2w=q2w$q2w_num  --nentries=$nentries
proc_h10.py --h10type=e1f:sim:2pi --output=d2pi --sim_num=sim1 --nentries=$nentries
echo ">>> ls -lrt $OBS_DATADIR_SIM/sim$sim_num/q2w$q2w_num"
ls -lrt $OBS_DATADIR_SIM/sim$sim_num/q2w$q2w_num
