#!/bin/bash
nentries=${1:-1000000000}
#ana -i h10.lst -t e1f:exp:2pi -p eid:efid:qskim:mom:pid:d2piR -n $nentries
#proc_h10.py --h10type=e1f:exp:2pi --output=d2pi --q2w=q2w1  --n=$nentries
#for i in `seq 1 49`;
#do
 #echo "*** Making exp/q2w$i/d2pi.root *** "
 logdir=$OBS_DATADIR/mem_test/exp/old-h8-bng
 rm $logdir/makelog
 rm $logdir/memlog
 proc_h10.py --h10type=e1f:exp:2pi --output=d2pi --n=$nentries >& $logdir/makelog&
 track_mem >& $logdir/memlog &
 #proc_h10.py --h10type=e1f:exp:2pi --output=d2pi --q2w=q2w$i --use_q2w_elist=True --n=$nentries
#done
