#!/bin/bash
#$1=Directory where h10 files are located.
if [[ -e h10.lst ]];then
  echo "h10.lst exists."
  exit
fi
if [[ -z "$1" ]]; then
 echo "Please enter directory where h10 files are located"
 exit
fi
for i in `ls $1/*.root | grep -v "ana"`;
do
 if [[ $HOST == "gothe14" ]]; then
  echo "$i" >> h10.lst
 elif [[ $HOST == *farm* ]]; then
  if [[ $1 == *mss* ]];then
    echo "/cache/$i" >> h10.lst
  else
    echo $i >> h10.lst 
  fi
 fi
done
