#!/bin/bash
sim_num=$1
q2w_num=$2
nentries=${3:-1000000000}

echo "*** Making /sim/sim$sim_num/q2w$q2w_num/d2pi.root *** "
echo ">>> ls -lrt $OBS_DATADIR_SIM/sim$sim_num/q2w$q2w_num"
ls -lrt $OBS_DATADIR_SIM/sim$sim_num/q2w$q2w_num
proc_h10.py --h10type=e1f:sim:2pi --output=d2pi --sim_num=sim$sim_num --q2w=q2w$q2w_num  --nentries=$nentries
echo ">>> ls -lrt $OBS_DATADIR_SIM/sim$sim_num/q2w$q2w_num"
ls -lrt $OBS_DATADIR_SIM/sim$sim_num/q2w$q2w_num
