#!/usr/bin/python
import subprocess 

q2wl=['q2w%i'%i for i in range(1,50)]
for q2w in q2wl:
#for q2w in ['q2w1','q2w2']:
	for dtyp in ['sim','exp']:
                cmd=["py",q2w,dtyp,'sim1']
                subprocess.call(cmd)
