#!/bin/bash

#! sim1.1: /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_200M_051815
#! sim2:   /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_300M_052015

simnamel=(2pi_200M_051815 2pi_300M_052015)
#! Following list obtained by ls /mss-path-to-sim/recon/*.root |grep -v ana |wc -l 
#! (Information matches what I originally noted in at-sim/README for each simulation)
sim_nfmssl=(1991 2987)

isim=0
for simname in "${simnamel[@]}";do
  nfmss=${sim_nfmssl[isim]}
  echo "Processing simnum:simname=$((isim + 1)):$simname"

  #! Check number .root files in $H10DIR_SIM/recon/
  echo '>nfvltl=$(ls $H10DIR_SIM_E16/$simname/recon/*.root |wc -l)'
  nfvltl=$(ls $H10DIR_SIM_E16/$simname/recon/*.root |wc -l)
  diff=$((nfmss-nfvltl))
  echo "simnum:simname:nfmss:nfvltl:diff=$((isim + 1)):$simname:$nfmss:$nfvltl:$diff"
  echo "***" 
  isim=$((isim + 1))
done

if [[ -n $1 && $1 == "touch" ]]; then
  echo "Going to touch simuluation data in /volatile"
  isim=0
  for simname in "${simnamel[@]}";do
    echo "touching simnum:simname=$((isim + 1)):$simname"
    for f in `ls $H10DIR_SIM_E16/$simname/recon/*.root`;do
      echo ">touch $f"
      touch $f
    done
    isim=$((isim + 1))
    echo "***"
  done
fi
