#!/usr/bin/python
import sys
sys.path.insert(0, '/home/trivedia/CLAS/workspace/ana2pi/elast_lite/obs_2pi')
from disp_obs import DispObs

#! ---------------------
#  dobs_1D [obsdir] [simnum=siml] [view=norm] [q2min=1.50] [q2max=5.00] [wmin=1.400] [wmax=2.125] [expt=e16] [dbg=False]
#!----------------------
#! Get obsdir
if len(sys.argv)==1:
        sys.exit("Please enter obsdir")
else:
        obsdir=sys.argv[1]

if len(sys.argv)>2: #! User input simnum, else use siml
	simnum=sys.argv[2]
else:
	simnum='siml'

if len(sys.argv)>3: #! User input view, else use view=norm 
	view=sys.argv[3]
	if view!="norm" and view!="fullana" and view!="ERyield" and view!="norm_EC_EF_SF":
		sys.exit("view=norm/fullana/ERyield/norm_EC_EF_SF only")
else:
	view="norm"	

if len(sys.argv)>4: #! User input q2min 
        q2min=float(sys.argv[4])
else:
        q2min=1.50

if len(sys.argv)>5: #! User input q2max 
        q2max=float(sys.argv[5])
else:
        q2max=5.00

if len(sys.argv)>6: #! User input wmin 
        wmin=float(sys.argv[6])
else:
        wmin=1.400

if len(sys.argv)>7: #! User input q2min 
        wmax=float(sys.argv[7])
else:
        wmax=2.125

if len(sys.argv)>8: #! User input expt 
        expt=sys.argv[8]
	if expt!='e1f' and expt!='e16':
		sys.exit("expt=e1f or e16 only.")
else:
        expt='e16'

if len(sys.argv)>9: #! User input dbg, else use dbg=False
	if sys.argv[9]=="False":
                dbg=False
        elif sys.argv[9]=="True":
                dbg=True
        else:
                print "Please enter dbg=True or False!"
                sys.exit()
else:
	dbg="False"

print "Displaying 1D-Obs for obsdir simnum view q2min q2max wmin wmax expt dbg",obsdir,simnum,view,q2min,q2max,wmin,wmax,expt,dbg
do=DispObs(obsdir,simnum,view,q2min,q2max,wmin,wmax,expt,dbg)
do.disp_1D()
if view=="norm":#! Integrated yield direct from h5 (currently implemented, for tech. reasons, only for norm=True)
	do.disp_itg_yld_drct_from_h5()
