#!/bin/bash

#! sim1.1: /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_200M_051815
#! sim2:   /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_300M_052015
#! sim3:   /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_500M_112315
#! sim4:   /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_500M_112715
#! sim5:   /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_500M_120915
#! sim6:   /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_121815
#! sim7:   /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_010216
#! sim8:   /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_010316
#! sim9:   /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_011216
#! sim10:  /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_011916
#! sim11:  /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_012916
#! sim12:  /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/2pi_1B_021016
#! sim13:  /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/2pi_1B_021716
#! sim14:  /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/2pi_1B_032516
#! sim15:  /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/2pi_1B_040816

simoutdirl=(/mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_200M_051815 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_300M_052015 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_500M_112315 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_500M_112715 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_500M_120915 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_121815 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_010216 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_010316 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_011216 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_011916 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_012916 /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/2pi_1B_021016 /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/2pi_1B_021716 /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/2pi_1B_032516 /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/2pi_1B_040816)

isim=0
for simoutdir in "${simoutdirl[@]}";do
  arr=(${simoutdir//\// })
  simname=${arr[${#arr[@]}-1]} #! simname=last element of array ${arr[-1]} does not work
  echo "simnum:simname=$((isim + 1)):$simname"
  if [[ $((isim + 1)) < 4 ]];then #! After deleting from volatile sim1.1,sim2,sim3
    echo "Not doing jget for simnum:simname=$((isim + 1)):$simname"
    echo "***"
    isim=$((isim + 1))
    continue
  fi

  #! Remove any existing file in $H10DIR_SIM
  echo ">rm $H10DIR_SIM_E16/$simname/recon/*.root"
  rm $H10DIR_SIM_E16/$simname/recon/*.root
  #! Now get files from /mss
  echo ">jget `ls $simoutdir/recon/*.root|grep -v ana` $H10DIR_SIM_E16/$simname/recon/ >& /tmp/atrivedi/jget_$simname.log&"
  jget `ls $simoutdir/recon/*.root|grep -v ana` $H10DIR_SIM_E16/$simname/recon/ >& /tmp/atrivedi/jget_$simname.log&
  
  isim=$((isim + 1))
done
