#!/bin/bash

#! sim1:   /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/3piPS_lQ2_100M_020217
#! sim2:   /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/3piPS_hQ2_100M_020217

simoutdirl=(/mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/3piPS_lQ2_100M_020217 /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/3piPS_hQ2_100M_020217)

isim=0
for simoutdir in "${simoutdirl[@]}";do
  arr=(${simoutdir//\// })
  simname=${arr[${#arr[@]}-1]} #! simname=last element of array ${arr[-1]} does not work
  echo "simnum:simname=$((isim + 1)):$simname"
  
  #! Remove any existing file in $H10DIR_SIM
  echo ">rm $H10DIR_SIM_E16/3pi-PS-sim/$simname/recon/*.root"
  rm $H10DIR_SIM_E16/3pi-PS-sim/$simname/recon/*.root
  #! Now get files from /mss
  echo ">jget `ls $simoutdir/recon/*.root|grep -v ana` $H10DIR_SIM_E16/3pi-PS-sim/$simname/recon/ >& /tmp/atrivedi/jget_$simname.log&"
  jget `ls $simoutdir/recon/*.root|grep -v ana` $H10DIR_SIM_E16/3pi-PS-sim/$simname/recon/ >& /tmp/atrivedi/jget_$simname.log&
  
  isim=$((isim + 1))
done
