#!/bin/bash

#! sim1.1: /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_200M_051815
#! sim2:   /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_300M_052015

simoutdirl=(/mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_200M_051815 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_300M_052015)

isim=0
for simoutdir in "${simoutdirl[@]}";do
  arr=(${simoutdir//\// })
  simname=${arr[${#arr[@]}-1]} #! does not work: ${arr[-1]}
  echo "simnum:simname=$((isim + 1)):$simname"

  #! Remove any existing file in $H10DIR_SIM
  echo ">rm $H10DIR_SIM_E16/$simname/recon/*.root"
  rm $H10DIR_SIM_E16/$simname/recon/*.root
  #! Now get files from /mss
  echo ">jget `ls $simoutdir/recon/*.root|grep -v ana` $H10DIR_SIM_E16/$simname/recon/ >& /tmp/atrivedi/jget_$simname.log&"
  jget `ls $simoutdir/recon/*.root|grep -v ana` $H10DIR_SIM_E16/$simname/recon/ >& /tmp/atrivedi/jget_$simname.log&
  
  isim=$((isim + 1))
done
