#!/bin/bash

#! sim1.1: /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_200M_051815
#! sim2:   /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_300M_052015
#! sim3:   /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_500M_112315
#! sim4:   /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_500M_112715
#! sim5:   /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_500M_120915
#! sim6:   /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_121815
#! sim7:   /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_010216
#! sim8:   /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_010316
#! sim9:   /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_011216
#! sim10:  /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_011916
#! sim11:  /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_012916
#! sim12:  /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/2pi_1B_021016
#! sim13:  /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/2pi_1B_021716
#! sim14:  /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/2pi_1B_032516
#! sim15:  /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/2pi_1B_040816

simoutdirl=(/mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_200M_051815 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_300M_052015 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_500M_112315 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_500M_112715 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_500M_120915 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_121815 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_010216 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_010316 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_011216 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_011916 /mss/home/atrivedi/batchdata/e16/2pi/sim/2pi_1B_012916 /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/2pi_1B_021016 /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/2pi_1B_021716 /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/2pi_1B_032516 /mss/clas/caa/atrivedi/batchdata/e16/2pi/sim/2pi_1B_040816)

isim=0
for simoutdir in "${simoutdirl[@]}";do
  arr=(${simoutdir//\// })
  simname=${arr[${#arr[@]}-1]} #! simname=last element of array ${arr[-1]} does not work
  simnum=$((isim + 1))
  echo "*** Processing simnum:simname=$simnum:$simname ***"
  if [ $simnum -lt 4 ];then #! After deleting from volatile sim1.1,sim2,sim3
     echo "Not doing jget for  simnum:simname=$simnum:$simname"
     echo "***"
     isim=$((isim + 1))
     continue
  fi

  #! [02-24-17] For some reason, for simnum=13 this script counted 0 files in mss, vltl, and therefore, mss_unique
  #! + Therefore, the following block of code was resued to run this script again for simnum=13 and then it worked
  #if [ $simnum -ne 13 ]; then
    #echo "simnum -ne 13 continuing"
    #isim=$((isim + 1))
    #continue
  #33fi

  #! Use 'comm' to find out which /mss file is missing in /volatile and use that to get missing files
  ls $simoutdir/recon/*.root               | xargs -n 1 basename > /tmp/atrivedi/"$simname"_mss.lst
  ls $H10DIR_SIM_E16/$simname/recon/*.root | xargs -n 1 basename > /tmp/atrivedi/"$simname"_vltl.lst
  comm -23 /tmp/atrivedi/"$simname"_mss.lst /tmp/atrivedi/"$simname"_vltl.lst > /tmp/atrivedi/"$simname"_mss_unique.lst
  nmissing=$(wc -l < /tmp/atrivedi/"$simname"_mss_unique.lst)
  echo "Number of files missing in /volatile="$nmissing
  echo "Submitting jget jobs to get these missing files..."
  for f in `cat /tmp/atrivedi/"$simname"_mss_unique.lst`
  do
    echo ">jget $simoutdir/recon/$f $H10DIR_SIM_E16/$simname/recon/ >& /tmp/atrivedi/jget_"$simname"_$f.log&"
    jget $simoutdir/recon/$f $H10DIR_SIM_E16/$simname/recon/ >& /tmp/atrivedi/jget_"$simname"_$f.log&
  done
  echo "Done submitting jget jobs to get these files. See logs for updates on these jobs."
  echo "***"
  
  isim=$((isim + 1))
done
