#!/bin/bash
expt=$1
seq=$2
rctn=$3
nentries=${4:-0}

#! Check if input data is ok
if [ $expt != 'e1f' ] && [ $expt != 'e16' ];then
  echo "expt=$expt is not valid"
  exit
fi
if [ $seq != 'ER' ] && [ $seq != 'ST' ] && [ $seq != 'SR' ];then
  echo "seq=$seq is not valid"
  exit
fi
if [ $rctn != '2pi' ] && [ $rctn != 'elast' ];then
  echo "rctn=$rctn is not valid"
  exit
fi

if [ $rctn == '2pi' ]; then
  if [ $seq == 'ER' ]; then
    dtyp="exp"
    procorder='eid:efid:pidnewmon:pfidnew:mom:q2wskimR:d2piR_tree'
  elif [ $seq == 'SR' ]; then
    dtyp="sim"
    procorder='eid:efid:pidnewmon:pfidnew:q2wskimR:d2piR_tree'
  elif [ $seq == 'ST' ]; then
    dtyp="sim"
    procorder='q2wskimT:d2piT_tree'
  fi
elif [ $rctn == 'elast' ]; then
  if [ $seq == 'ER' ]; then
    dtyp="exp"
    procorder='eid:efidnew:mom:delastR_tree'
  elif [ $seq == 'SR' ]; then
    dtyp="sim"
    procorder='eid:efidnew:delastR_tree'
  elif [ $seq == 'ST' ]; then
    dtyp="sim"
    procorder='delastT_tree'
  fi
fi

echo "expt="$expt
echo "seq="$seq
echo "rctn="$rctn
echo "dtyp="$dtyp
echo "procorder="$procorder
echo "nentries="$nentries

echo ">proc_h10 -i h10"$seq".lst -t $expt:$dtyp:$rctn  -p $procorder -o d"$rctn""$seq"_ddetineff.root -n $nentries"
proc_h10 -i h10"$seq".lst -t $expt:$dtyp:$rctn  -p $procorder -o d"$rctn""$seq"_ddetineff.root -n $nentries
