#!/bin/bash
# $1 = Top. Number
# $2 = exp/sim

# makepdf for hRvVar
echo $1 
ls -d polobs3_dnp/top$1/*/*/*/RvVar.png  > /tmp/tmp3
sed -i "s@^@$(pwd)/@" /tmp/tmp3
sed -i "s/\/RvVar.png//g" /tmp/tmp3  

for i in `cat /tmp/tmp3`
do
  convert $i/RvVar.png $i/RvVar.pdf 
done

ls polobs3_dnp/top$1/*/*/*/RvVar.pdf > /tmp/tmppdf3
sed -i "s@^@$(pwd)/@" /tmp/tmppdf3
echo "./polobs3_dnp/RvVar_top$1.pdf" >> /tmp/tmppdf3
cat /tmp/tmppdf3 | xargs pdfunite
