#!/usr/bin/python
from proc_yields_lite import ProcYieldsLite
from disp_yields_lite import DispYieldsLite
import sys

'''
dy_integ [obsdir] [simnum=siml] [topcmbns=1:2:3:4]
'''
#! Get obsdir
if len(sys.argv)==1:
        sys.exit("Please enter obsdir")
else:
        obsdir=sys.argv[1]

#! User input simnum, else use siml
if len(sys.argv)>2:
	simnum=sys.argv[2]
else:
	simnum='siml'

topcmbnl=[]
if len(sys.argv)>3:#i.e. topcmbns by user
        topcmbns=sys.argv[3].split("_")
        if len(topcmbns)>0:
                for topcmbn in topcmbns:
                        topcmbn=topcmbn.split(':')
                        topcmbn=map(int,topcmbn)
                        #print "top=",top
                        for top in topcmbn:
                                if top!=1 and top!=2 and top!=3 and top!=4:
                                        sys.exit("Please enter each top as 1:2 or 2 or 1:2:3:4 etc")
                        topcmbnl.append(topcmbn)
        else:
                sys.exit("Please enter topcmbns as 1:2;2;1:2:3:4")
else:
        topcmbnl.append([1,2,3,4])

#print "Displaying integrated yields for obsdir:sim:topcmbns = %s:%s:%s"%(obsdir,simnum,topcmbnl)
print "Displaying integrated yields for obsdir:sim = %s:%s"%(obsdir,simnum)

#for topcmbn in topcmbnl:
dy=DispYieldsLite(obsdir,simnum=simnum)
dy.disp_integ_yield(vst='VST1',norm=True)
#dy.disp_integ_yield(vst='VST2',norm=True)
#dy.disp_integ_yield(vst='VST3',norm=True)
