#!/bin/bash 
if [ -z $1 ];then
  echo "enter beam energy!"
  exit
fi
BE=be$1
  
ROOTDIR=/e1f.sim2pi.datadir/setup_sim_CentOS6/gpppars/try1
for i in $(ls -d $ROOTDIR/q2w2_gpptest_*/);
do
 RECONDIR=${i%%/}/recon
 echo $RECONDIR
 cd $RECONDIR
 ls *.root > h10.lst 
 ana_e1f.sim.2pi 
 cp d2pi.root d2pi_$BE.root
done
